# -*- coding: utf-8 -*-
"""Timed scenes per chapter. Times are fractions of the narration, so they hold
   whatever the final audio length turns out to be."""
SCENES = {
"edge": [
 (0.00,"Chapter two","Where the edge came from",None,None),
 (0.08,None,"No course. No certificate.","It was YouTube, and copying what people did.",None),
 (0.26,"The filter","Watch the ones that break","Anyone can film a tool working.",None),
 (0.42,"Rule one","Have it open while you watch","Passive viewing teaches vocabulary and nothing else.",None),
 (0.58,"Rule two","One tool. One month.","Depth beats a tour of nine.",None),
 (0.74,"Rule three","Check the upload date","Six months is history, not instruction.",None),
 (0.88,None,"16 videos · 4 channels",None,["START HERE","GO DEEPER","STAY CURRENT"]),
],
"agentic": [
 (0.00,"Chapter three","From answering, to doing",None,None),
 (0.07,"Before","A very fast writer with no hands","You asked. It answered. You did the work.",None),
 (0.22,"What changed","It stopped answering and started acting",None,None),
 (0.33,"In practice","You give an outcome","It works out the route itself.",None),
 (0.52,"All four, or none","Goal · Tools · Loop · Memory",None,["OUTCOME","REAL TOOLS","A LOOP","MEMORY"]),
 (0.74,None,"Take one away","and you have a chatbot with extra steps.",None),
 (0.86,"The frame","A staff officer","Capable, quick, and dependent on you for direction.",None),
],
"pricing": [
 (0.00,"Chapter four","What the toolkit costs",None,None),
 (0.06,None,"7","tools in this chapter. You need about two.",None),
 (0.18,"The number","$20","is what everyone converged on.",None),
 (0.30,"Each one",None,None,["ChatGPT","Claude","Perplexity","Gemini"]),
 (0.52,"Students","$10","Perplexity Education Pro. Almost nobody claims it.",None),
 (0.70,None,"Gemini Notebook","answers only from sources you upload.",None),
 (0.84,"Remember","Nothing is unlimited","Every $200 tier is metered.",None),
 (0.94,None,"Prices moved 4× last quarter","Check before you quote me.",None),
],
"skills": [
 (0.00,"Chapter five","Why prompting is dead",None,None),
 (0.10,None,"Magic phrases were a workaround","for models that could not follow instructions.",None),
 (0.24,"What replaced it","Stop writing steps","Start stating the end state.",None),
 (0.38,"Every delegation",None,None,["END STATE","CONSTRAINTS","A TEST"]),
 (0.58,"You know this","Mission command","Intent, bounds, freedom of action, back-brief.",None),
 (0.72,"A skill","A folder of written instructions","It loads only when a task matches.",None),
 (0.88,"The trick","“Turn that into a skill”","Then cut half of what it wrote.",None),
],
"plumbing": [
 (0.00,"Chapter six","The plumbing",None,None),
 (0.08,"Before MCP","3 models × 3 tools = 9 builds",None,None),
 (0.22,"After","Write it once","Any model can use it.",None),
 (0.34,"Connectors","Sockets already wired",None,["GMAIL","DRIVE","NOTION","SLACK","GITHUB"]),
 (0.50,None,"Grant narrowly. Revoke after.",None,None),
 (0.60,"The warning","Local does not mean private",None,None),
 (0.76,None,"The hands are local","The reasoning is not.",None),
 (0.88,None,"If you would not email it to a vendor","do not prompt it.",None),
],
"research": [
 (0.00,"Chapter seven","Research that survives a marker",None,None),
 (0.07,None,"It looks perfect","Right author. Right journal. No such paper.",None),
 (0.22,"Why","A citation is what usually follows a claim","So it produces one. Attached to nothing.",None),
 (0.40,"One rule","A citation comes from a result you can click",None,None),
 (0.54,"The expensive one","A real paper, for a claim it never makes","That one survives a quick check.",None),
 (0.70,"So check twice",None,None,["DOES IT EXIST","DOES IT SAY THAT"]),
 (0.82,"Stop asking","“Summarise this”","Everybody else gets the same one.",None),
 (0.92,None,"What would change your answer?",None,None),
],
"decks": [
 (0.00,"Chapter eight","Formats, and what a folder lets you ask",None,None),
 (0.08,None,"Ask for a deck, get generic slides","Design is where it is weakest.",None),
 (0.22,"Instead","Hand it your format","Then let it fill it.",None),
 (0.40,None,"Settle the argument first","Decks built before the argument are filler.",None),
 (0.54,"The underrated part","It can read a whole folder","Not one file. Everything.",None),
 (0.70,"The question",None,"“My last six essays and the feedback. What do I keep getting wrong?”",None),
 (0.86,"Two rules",None,None,["IT ALL LEAVES YOUR MACHINE","MAKE IT PROPOSE FIRST"]),
],
}
