# -*- coding: utf-8 -*-
"""Timed scenes per chapter. Times are fractions of the narration, so they hold
   whatever the final audio length turns out to be."""
SCENES = {
"edge": [
 (0.00,"Chapter two","Where the edge came from",None,None),
 (0.03,None,"The honest version is boring","It was YouTube, and copying what people did.",None),
 (0.25,"The filter","Watch the ones that break","Anyone can film a tool working.",None),
 (0.49,"Rule one","Have it open while you watch","Passive viewing teaches vocabulary and nothing else.",None),
 (0.63,"Rule two","One tool for a month","Depth in one beats a tour of nine.",None),
 (0.76,"Rule three","Check the upload date","Past six months, the buttons have almost certainly moved.",None),
 (0.88,None,"16 videos · 4 channels",None,["START HERE","GO DEEPER","STAY CURRENT"]),
],
"agentic": [
 (0.00,"Chapter three","From answering to doing",None,None),
 (0.08,"Before","A very fast writer with no hands","It answered your question and you did the work yourself.",None),
 (0.21,"What changed","It stopped answering and started acting",None,None),
 (0.26,"In practice","You give an outcome","It works out the route itself.",None),
 (0.45,"All four, or none","Goal · Tools · Loop · Memory",None,["OUTCOME","REAL TOOLS","A LOOP","MEMORY"]),
 (0.60,None,"Take one away","and you have a chatbot with extra steps.",None),
 (0.64,"The frame","A staff officer","Capable and quick, but dependent on you for direction.",None),
 (0.71,"Your job","Set the intent and the bounds","Then check the work. That is now most of the job.",None),
 (0.88,"The catch","A wrong agent reads like a right one","It sounds equally fluent and sure.",None),
 (0.97,None,"You check it yourself","every single time.",None),
],
"pricing": [
 (0.00,"Chapter four","What the toolkit costs",None,None),
 (0.04,None,"7","tools in this chapter. You need about two.",None),
 (0.08,"The number","$20","is what everyone converged on.",None),
 (0.19,"Each one",None,None,["ChatGPT","Claude","Perplexity","Gemini"]),
 (0.49,"Students","$10","Perplexity Education Pro. Almost nobody claims it.",None),
 (0.63,None,"Gemini Notebook","answers only from sources you upload.",None),
 (0.81,"Remember","Even the $200 plans run out","ChatGPT and Claude both meter them.",None),
 (0.95,None,"Prices change all the time","Check before you quote me.",None),
],
"skills": [
 (0.00,"Chapter five","Why prompting is dead",None,None),
 (0.06,None,"Magic phrases were a workaround","for models that could not follow instructions.",None),
 (0.17,"What replaced it","State the end state","The model finds its own route.",None),
 (0.31,"Every delegation",None,None,["END STATE","CONSTRAINTS","A TEST"]),
 (0.55,"You know this","Mission command","Intent, bounds, freedom of action, back-brief.",None),
 (0.69,"A skill","A folder of written instructions","It loads only when a task matches.",None),
 (0.85,"The trick","“Turn that into a skill”","Then cut half of what it wrote.",None),
],
"plumbing": [
 (0.00,"Chapter six","The plumbing",None,None),
 (0.08,"First idea","MCP","Model Context Protocol. Anthropic published it in late 2024 and gave it away.",None),
 (0.19,"Before MCP","3 models × 3 tools = 9 builds",None,None),
 (0.28,"After","Write it once","Any model can use it.",None),
 (0.37,"Connectors","Sockets already wired",None,["GMAIL","DRIVE","NOTION","SLACK","GITHUB"]),
 (0.48,None,"Grant the narrowest permission","then revoke it when the job is finished.",None),
 (0.53,"The warning","Local and cloud","Almost everybody gets the difference backwards.",None),
 (0.63,"Local","The hands are on your machine","It can read your real files and run real commands.",None),
 (0.70,"Remember","Local does not mean private","The reasoning runs on servers that belong to somebody else.",None),
 (0.82,"The rule","It has not changed","Classified and marked material, work documents and other people’s personal data stay out, on every tier.",None),
 (0.97,None,"If you would not email it to a vendor","do not prompt it.",None),
],
"research": [
 (0.00,"Chapter seven","Research that survives a marker",None,None),
 (0.03,None,"It looks perfect","Right author and journal, but no such paper.",None),
 (0.16,"Why","A citation is what usually follows a claim","So the model produces one, attached to nothing.",None),
 (0.41,"One rule","A citation comes from a result you can click",None,None),
 (0.54,"The expensive one","A real paper, for a claim it never makes","That one survives a quick check.",None),
 (0.65,"So check twice",None,None,["DOES IT EXIST","DOES IT SAY THAT"]),
 (0.75,"Stop asking","“Summarise this”","Everybody else gets the same one.",None),
 (0.95,None,"What would change your answer?",None,None),
],
"decks": [
 (0.00,"Chapter eight","Formats, and what a folder lets you ask",None,None),
 (0.04,None,"Ask for a deck, get generic slides","Design is where it is weakest.",None),
 (0.12,"The fix","Hand it your format","Then let it fill it.",None),
 (0.37,None,"Settle the argument first","Decks built before the argument are filler.",None),
 (0.46,"The underrated part","It can read a whole folder","Every file, with the structure intact.",None),
 (0.70,"The question",None,"“My last six essays and the feedback. What do I keep getting wrong?”",None),
 (0.84,"Two rules",None,None,["IT ALL LEAVES YOUR MACHINE","MAKE IT PROPOSE FIRST"]),
],
}
